export const siteConfig = {
  name: "Felipe Jovino",
  shortName: "Jovino",
  fullName: "Felipe Jovino dos Santos",
  title: "Felipe Jovino — Coordenador de TI, CTO & Pesquisador AI",
  description:
    "Coordenador de TI na WM Saúde, CTO & Co-Founder da AccessSim e pesquisador em Inteligência Artificial. Construindo soluções escaláveis que unem engenharia de software de ponta, deeptech e liderança técnica.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://felipejovino.dev",
  locale: "pt-BR",
  jobTitle: "Coordenador de TI | CTO & Co-Founder | Pesquisador AI & Deeptech",
  email: "felipejovinogamerplay@gmail.com",
  whatsapp: {
    display: "+55 79 9988-0776",
    url: "https://wa.me/557999880776",
  },
  authorImage: "/og-image.png",
  ogImage: "/og-image.png",
  keywords: [
    "Felipe Jovino",
    "Coordenador de TI",
    "CTO",
    "Engenheiro Full-Stack",
    "Pesquisador IA",
    "Next.js",
    "AdonisJS",
    "Rust",
    "Deeptech",
    "Acessibilidade",
    "AccessSim",
    "WM Saúde",
    "WF3 Solutions",
    "Masters Tech",
    "Mestrado UFS PROCC",
    "INPI Glicemy",
  ],
  social: {
    github: "https://github.com/Jovinull",
    linkedin: "https://www.linkedin.com/in/jobas",
    youtube: "https://www.youtube.com/@MastersTech",
    twitter: "@felipejovino",
  },
  alumniOf: ["UFS — PROCC (Mestrado em Computação)"],
  knowsAbout: [
    "Next.js",
    "React",
    "AdonisJS",
    "Node.js",
    "Python",
    "Java",
    "Spring Boot",
    "PostgreSQL",
    "Docker",
    "Azure",
    "AWS",
    "Machine Learning",
    "Redes Neurais",
    "Keras",
    "ESP32",
    "IoT",
    "MQTT",
    "Acessibilidade",
    "NBR 9050",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
